-- 1️⃣ Switch to SYSADMIN role
USE ROLE SYSADMIN;

-- 2️⃣ Create a Virtual Warehouse
CREATE WAREHOUSE SNOWPARK_ETL_WH 
    WITH 
    WAREHOUSE_SIZE = 'MEDIUM' 
    WAREHOUSE_TYPE = 'STANDARD' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE 
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1 
    SCALING_POLICY = 'STANDARD';

-- 3️⃣ Verify roles and warehouses
SHOW ROLES;
SHOW WAREHOUSES;

-- 4️⃣ Switch to ACCOUNTADMIN (needed for user creation)
USE ROLE ACCOUNTADMIN;

-- 5️⃣ Create a Snowpark user
CREATE USER SNOWPARK_USER 
  PASSWORD = 'Test@12345' 
  COMMENT = 'This is Snowpark user' 
  DEFAULT_ROLE = SYSADMIN
  DEFAULT_SECONDARY_ROLES = ('ALL')
  MUST_CHANGE_PASSWORD = FALSE;

-- 6️⃣ Grant SYSADMIN role to the user
GRANT ROLE SYSADMIN TO USER SNOWPARK_USER;

-- 7️⃣ Grant warehouse access
GRANT USAGE ON WAREHOUSE SNOWPARK_ETL_WH TO ROLE SYSADMIN;

-- 8️⃣ Grant database & schema access to SYSADMIN
GRANT USAGE ON DATABASE SALES_DWH TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- 9️⃣ Grant SELECT on all existing tables
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- 🔄 Ensure future tables are accessible
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- 🔎 Verify setup
SELECT CURRENT_WAREHOUSE();
SHOW DATABASES LIKE 'SALES_DWH';
SHOW SCHEMAS IN SALES_DWH;
SHOW GRANTS TO USER SNOWPARK_USER;
SHOW GRANTS ON DATABASE SALES_DWH;

USE ROLE ACCOUNTADMIN;


-- Give SYSADMIN full ownership of the database (so it has full control over schemas, tables, and stages).
-- 1️⃣ Switch to ACCOUNTADMIN to perform ownership transfer
USE ROLE ACCOUNTADMIN;

-- 2️⃣ Check existing grants (to see what needs revoking)
SHOW GRANTS ON DATABASE SALES_DWH;
SHOW GRANTS ON SCHEMA SALES_DWH.SOURCE;

-- 3️⃣ Revoke existing dependent grants before ownership transfer
REVOKE USAGE ON SCHEMA SALES_DWH.SOURCE FROM ROLE SYSADMIN;
REVOKE USAGE ON DATABASE SALES_DWH FROM ROLE SYSADMIN;

-- 4️⃣ Transfer ownership of the database to SYSADMIN
GRANT OWNERSHIP ON DATABASE SALES_DWH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

-- 5️⃣ Transfer ownership of all schemas inside SALES_DWH
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE SALES_DWH TO ROLE SYSADMIN;
GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE SALES_DWH TO ROLE SYSADMIN;

-- 6️⃣ Restore privileges after ownership change
GRANT ALL PRIVILEGES ON DATABASE SALES_DWH TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- 7️⃣ Ensure SYSADMIN has full control over all tables, views, and stages
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
-- GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
-- GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- 🔎 Verify setup
SHOW GRANTS ON DATABASE SALES_DWH;
SHOW GRANTS ON SCHEMA SALES_DWH.SOURCE;



-- USE ROLE ACCOUNTADMIN;

-- -- 6️⃣ Grant SYSADMIN role to the user
-- GRANT ROLE SYSADMIN TO USER SNOWPARK_USER;

-- -- 7️⃣ Grant SYSADMIN full control over SALES_DWH
-- -- GRANT OWNERSHIP ON DATABASE SALES_DWH TO ROLE SYSADMIN;
-- GRANT OWNERSHIP ON DATABASE SALES_DWH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;


-- -- 8️⃣ Grant SYSADMIN full control over schemas
-- GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE SALES_DWH TO ROLE SYSADMIN REVOKE CURRENT GRANTS;
-- GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE SALES_DWH TO ROLE SYSADMIN;

-- -- 9️⃣ Grant SYSADMIN full control over all tables, views, and stages
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
-- GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
-- GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA SALES_DWH.SOURCE TO ROLE SYSADMIN;

-- -- 🔎 Verify setup
-- SELECT CURRENT_WAREHOUSE();
-- SHOW DATABASES LIKE 'SALES_DWH';
-- SHOW SCHEMAS IN SALES_DWH;
-- SHOW GRANTS TO USER SNOWPARK_USER;
-- SHOW GRANTS ON DATABASE SALES_DWH;

-- USE ROLE ACCOUNTADMIN;

SHOW STAGES IN SCHEMA SALES_DWH.SOURCE;
GRANT USAGE, READ, WRITE ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG TO ROLE SYSADMIN;
SHOW GRANTS ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG;


CREATE STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG;


USE ROLE ACCOUNTADMIN;
SHOW GRANTS ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG;
GRANT READ, WRITE ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG TO ROLE SYSADMIN;
GRANT OWNERSHIP ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG TO ROLE SYSADMIN REVOKE CURRENT GRANTS;

USE ROLE SYSADMIN;
SHOW GRANTS ON STAGE SALES_DWH.SOURCE.MY_INTERNAL_STG;



